# Generated by Django 2.2.7 on 2019-11-22 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='occupation',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
