# Generated by Django 2.2.7 on 2019-11-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw', '0003_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='occupation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
