# Generated by Django 2.2.7 on 2019-11-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw', '0004_auto_20191122_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
