# Generated by Django 2.2.7 on 2019-11-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw', '0005_message_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
    ]
